@startuml Abstract factory vs Factory Method

package FactoryMethod {
  class PizzaStore {
    + Pizza createPizza()
    + payment()
  }
  note left
  We have a Pizza store which it sells
    two kinds of pizza but their payments 
    process are same. so this abstract class
    handle main business logic related to the 
    same logics of all kinds products
  end note

  interface Pizza {}
  note bottom
  This interface declare methods that all
    concrete pizza products should 
    implement them 
  end note

  PizzaStore ..> Pizza

  class NYPizzaStore {
    + Pizza createPizza()
  }
  note left
  This is one of our factory methods
    that extends from base abstract factory.
  It's main responsibility is to be a factory
    for creating one kind of products
  end note
  NYPizzaStore --|> PizzaStore
  NYPizzaStore --> NYstylePepperoniPizza

  class ChicagoPizzaStore {
    + Pizza createPizza()
  }
  note left
  This is one of our factory methods
    that extends from base abstract factory.
  It's main responsibility is to be a factory
    for creating one kind of products
  end note
  ChicagoPizzaStore --|> PizzaStore
  ChicagoPizzaStore --> ChicagoStylePepperoniPizza

  class client{}
  client --> ChicagoPizzaStore
  client --> NYPizzaStore

  class NYstylePepperoniPizza {}
  note bottom
  This is one of a concrete pizza products
    that implements Pizza interface. 
  This will handle all logics about creating 
    this kind of pizza
  It will instantiated by one related factories.
  end note
  NYstylePepperoniPizza ..|> Pizza
  class ChicagoStylePepperoniPizza{}
  note bottom
  This is one of a concrete pizza products
    that implements Pizza interface. 
  This will handle all logics about creating 
    this kind of pizza
  It will instantiated by one related factories.
  end note
  ChicagoStylePepperoniPizza ..|> Pizza
}


package AbstractFactory {
  interface PizzaIngredientsFactory {
    + Dough createDough()
    + Sauce createSauce()
    + Cheese createCheese()
  }
  note top
  This interface declares mehthods which
    makes abstract products.
  Each family can implement and create 
    products related to their own type. 
  end note

  class NYPizzaIngredientFactory {
    + Dough createDough()
    + Sauce createSauce()
    + Cheese createCheese()
  }
  note top
  This is a family factory which it implements our 
    main interface of needed abstract product
  end note
  NYPizzaIngredientFactory ..|> PizzaIngredientsFactory

  class ChicagoPizzaIngredientFactory {
    + Dough createDough()
    + Sauce createSauce()
    + Cheese createCheese()
  }
  note top
  This is a family factory which it implements our 
    main interface of needed abstract product
  end note
  ChicagoPizzaIngredientFactory ..|> PizzaIngredientsFactory

  interface Dough {}
  interface Sauce {}
  interface Cheese {}

  class ThinCrustDough {}
  note bottom
  Each ingredient represents a product that is produced
   by a Factory Method in the Abstract Factory.
  end note
  ThinCrustDough ..|> Dough
  class ThickCrustDough {}
  ThickCrustDough ..|> Dough

  class MarinaraSauce {}
  MarinaraSauce ..|> Sauce

  class PlumTomatoSauce {}
  PlumTomatoSauce ..|> Sauce

  class ReggianoCheese {}
  ReggianoCheese ..|> Cheese

  class MozzarellaCheese {}
  MozzarellaCheese ..|> Cheese

  ChicagoPizzaIngredientFactory --> MozzarellaCheese  
  ChicagoPizzaIngredientFactory --> PlumTomatoSauce  
  ChicagoPizzaIngredientFactory --> ThickCrustDough 

  NYPizzaIngredientFactory -->  ThinCrustDough
  NYPizzaIngredientFactory -->  MarinaraSauce
  NYPizzaIngredientFactory -->  ReggianoCheese

  class client {}
  client --> NYPizzaIngredientFactory
  client --> ChicagoPizzaIngredientFactory
}

@enduml