@startuml App MVVM class diagram
  class View {}
  note top
    Responsible for UI
  end note

  class IVM {}
  note bottom 
    Covention between UI and UI logics
  end note
  View ..> IVM: has

  class VM {
    IVM useVM()
  }
  note top
    Handles UI logic based on IVM interface
  end note

  VM --> IVM: is

  class SomeHigherLevelView {}
  note top
    This is a higher level component which needs to use that view so
      it connects View to VM
  end note
  SomeHigherLevelView --> VM: has
  SomeHigherLevelView --> View: has
@enduml
